#!/usr/bin/python

# require's polib from https://bitbucket.org/izi/polib/wiki/Home
#
#   python-polib rpm or "easy_install polib"
#
#  cmp_pot_files po/old_keys.pot po/new_keys.pot
#
#  Should show any new strings between the two revs


import glob
import polib
import sys


pot_file1 = sys.argv[1]
pot_file2 = sys.argv[2]

p1 = polib.pofile(pot_file1)
p2 = polib.pofile(pot_file2)

strings1 = {}
for e1 in p1.untranslated_entries():
    strings1[e1.msgid] = e1

strings2 = {}
for e2 in p2.untranslated_entries():
    strings2[e2.msgid] = e2

#print "Added"
for msg in strings1:
    if msg not in strings2:
        print strings1[msg]

#print "Removed"
#for msg in strings2:
#    if msg not in strings1:
#        print strings2[msg]
