#!/bin/bash

# git changed-strings rev1 rev2 [potfile]
# given two rev's and an optional path to a po template/string catalog/pot file
# shows you the new strings in a useful format
# (as opposed to the useless git diff )


GCS_TMPDIR=$(mktemp -d)

# our default
POFILE="po/keys.pot"

# third arg for path if not the default
if [ -n "$3" ]; then
   POFILE="$3"
fi

REV1="$GCS_TMPDIR/rev1.pot"
REV2="$GCS_TMPDIR/rev2.pot"

git show "$1":"$POFILE" > $REV1
git show "$2":"$POFILE" > $REV2

cmp_pot_files $REV1 $REV2

# cleanup
rm -rf $GCS_TMPDIR