#!/bin/bash



usage() {
	print "show-bugs [-s|--status] bug_status [-w|--web] log_options"
}

status=
log_opts=
while [ "$1" != "" ]; do
    case $1 in
        -s | --status )         shift
                                status=$1
                                ;;
        -w | --web )            web=1
                                ;;
        -h | --help )           usage
                                exit
                                ;;
    esac
    log_opts="${log_opts} ${1}"
    shift
done

buglist() { 
for bug in $(git log --format="format:%s" --grep "^[[:digit:]]\\+:"  $log_opts | awk -F":" '{print $1 }') 
do
	 echo -n $bug, 
done
};

open_browser()
{
	xdg-open "https://bugzilla.redhat.com/buglist.cgi?bug_id=$1;bug_status=$2" ;
};


if [ "$web" == "1" ] ; then
	open_browser $(buglist) "$status" > /dev/null 2>&1
else
	bugzilla query --bug_status "$status" -b $(buglist) 
fi
