#!/bin/bash


status=
exclude=
while [ "$1" != "" ]; do
    case $1 in
        -x | --exclude )        shift
                                exclude=$1
                                ;;
    esac
    shift
done

grep_opts="."

if [ -n "$exclude" ] ; then
	grep_opts="-v $exclude"
fi

git ls-files | grep $grep_opts | while read line;
do
	git blame -f -e "$line";
done | awk '{print $3 }' | sort |perl -pe "s/\(\<(.+\@.+)\>+/\1/; " | uniq -c | sort -n


