#!/bin/bash
#
# Show a colurful list of git branches sorted by last commit date.
#
# Think of it as the 'ls -lart' of 'git branch'
#
# Adrian Likins <adrian@likins.com>
#
# https://github.com/alikins/gitconfig
#
# License: GPLv2


# default:relative, :short, :local, :iso8601, :rfc2822 or :raw to the end of the fieldname; e.g.
#        %(taggerdate:relative).
# %(upstream:short)
#

    #--format="%1B[0;34m%(authordate:iso8601)%1B[m %1B[0;32m%(refname:short)%1B[m   %(subject)" "${REFS}"
REFS=${1:-refs/heads}
git for-each-ref --sort=committerdate \
    --format="%1B[0;34m%(authordate:iso8601)%1B[m %1B[0;32m%(refname:short)%1B[m  %(subject)" "${REFS}"
