#!/bin/bash
#
# Show a colurful list of git branches sorted by last commit date.
#
# Think of it as the 'ls -lart' of 'git branch'
#
# Adrian Likins <adrian@likins.com>
#
# https://github.com/alikins/gitconfig
#
# License: GPLv2

REFS=${1:-refs/heads}
git for-each-ref --sort=committerdate \
    --format="%1B[0;33m%(authordate:relative)%1B[m %1B[0;34m%(refname:short)%1B[m -  %(subject)" "${REFS}"
